-- MySQL Script generated by MySQL Workbench
-- Mon Nov 12 00:17:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema usurus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usurus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usurus` DEFAULT CHARACTER SET utf8 ;
USE `usurus` ;

-- -----------------------------------------------------
-- Table `usurus`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usurus`.`Area` (
  `idArea` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `tipoArea` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usurus`.`Hardware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usurus`.`Hardware` (
  `serie` VARCHAR(60) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `numeroInventario` VARCHAR(10) NOT NULL,
  `Area_idArea` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`serie`, `Area_idArea`),
  INDEX `fk_Hardware_Area1_idx` (`Area_idArea` ASC),
  CONSTRAINT `fk_Hardware_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `usurus`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usurus`.`Licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usurus`.`Licencia` (
  `idLicencia` VARCHAR(10) NOT NULL,
  `numeroLicencias` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `clave` VARCHAR(40) NOT NULL,
  `proveedor` VARCHAR(50) NOT NULL,
  `caracter` VARCHAR(20) NOT NULL,
  `tipoLicenciamiento` VARCHAR(45) NOT NULL,
  `Hardware_serie` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idLicencia`, `Hardware_serie`),
  INDEX `fk_Licencia_Hardware1_idx` (`Hardware_serie` ASC),
  CONSTRAINT `fk_Licencia_Hardware1`
    FOREIGN KEY (`Hardware_serie`)
    REFERENCES `usurus`.`Hardware` (`serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usurus`.`Software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usurus`.`Software` (
  `idSoftware` VARCHAR(10) NOT NULL,
  `monto` DOUBLE NOT NULL,
  `nombre` VARCHAR(70) NOT NULL,
  `version` VARCHAR(10) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `origen` ENUM('adquirido', 'desarrollado', 'donado', 'particular', 'asociado') NOT NULL,
  `tipo` ENUM('tecnico', 'laboratorio', 'administrativo', 'investigacion') NOT NULL,
  `descripcion` LONGTEXT NULL,
  `Licencia_idLicencia` INT NOT NULL,
  PRIMARY KEY (`idSoftware`, `Licencia_idLicencia`),
  INDEX `fk_Software_Licencia1_idx` (`Licencia_idLicencia` ASC),
  CONSTRAINT `fk_Software_Licencia1`
    FOREIGN KEY (`Licencia_idLicencia`)
    REFERENCES `usurus`.`Licencia` (`idLicencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usurus`.`Responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usurus`.`Responsable` (
  `numeroPersonal` VARCHAR(10) NOT NULL,
  `correoElectronico` VARCHAR(100) NOT NULL,
  `entidadAcademica` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`numeroPersonal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usurus`.`Resguardo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usurus`.`Resguardo` (
  `idResguardo` VARCHAR(10) NOT NULL,
  `horaPrestamo` DATE NOT NULL,
  `horaDevolucion` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `Hardware_serie` VARCHAR(60) NOT NULL,
  `Responsable_numeroPersonal` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idResguardo`, `Hardware_serie`, `Responsable_numeroPersonal`),
  INDEX `fk_Resguardo_Hardware1_idx` (`Hardware_serie` ASC),
  INDEX `fk_Resguardo_Responsable1_idx` (`Responsable_numeroPersonal` ASC),
  CONSTRAINT `fk_Resguardo_Hardware1`
    FOREIGN KEY (`Hardware_serie`)
    REFERENCES `usurus`.`Hardware` (`serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resguardo_Responsable1`
    FOREIGN KEY (`Responsable_numeroPersonal`)
    REFERENCES `usurus`.`Responsable` (`numeroPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usurus`.`TecnicoAcademico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usurus`.`TecnicoAcademico` (
  `numeroPersonal` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(90) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correoElectronico` VARCHAR(100) NOT NULL,
  `entidadAcademica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numeroPersonal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usurus`.`Dictamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usurus`.`Dictamen` (
  `idDictamen` VARCHAR(10) NOT NULL,
  `fechaDictamen` DATE NULL,
  `tipo` VARCHAR(20) NULL,
  `observacion` LONGTEXT NULL,
  `descripcion` LONGTEXT NULL,
  `Hardware_serie` VARCHAR(60) NOT NULL,
  `TecnicoAcademico_numeroPersonal` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idDictamen`, `Hardware_serie`, `TecnicoAcademico_numeroPersonal`),
  INDEX `fk_Dictamen_Hardware_idx` (`Hardware_serie` ASC),
  INDEX `fk_Dictamen_TecnicoAcademico1_idx` (`TecnicoAcademico_numeroPersonal` ASC),
  CONSTRAINT `fk_Dictamen_Hardware`
    FOREIGN KEY (`Hardware_serie`)
    REFERENCES `usurus`.`Hardware` (`serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dictamen_TecnicoAcademico1`
    FOREIGN KEY (`TecnicoAcademico_numeroPersonal`)
    REFERENCES `usurus`.`TecnicoAcademico` (`numeroPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
